export type FAQ = { q: string; a: string };

export const faqs: FAQ[] = [
  { q: "What is the typical turnaround time for sterility testing?", a: "Standard USP <71> / ISO 11737-2 sterility testing requires a 14-day incubation. The clock starts the day samples are received. For Boulder Sterilization clients, samples are received the same day the cycle ends — eliminating the 2-5 day inbound transit window typical of national labs." },
  { q: "Do you offer rapid sterility / fast cycle release?", a: "Yes — Boulder BioLabs offers 4-hour cycle release using 3M Attest rapid-readout biological indicators (BIs). Compared to Nelson Labs' 6-day rapid microbiological method (RMM) or traditional 7-day BI incubation, the 3M Attest 4-hour platform confirms sterilization cycle efficacy via fluorescence detection within four hours of cycle end. For BI-based release programs (common in EO, CD, and steam sterilization release), devices can be released within hours of cycle completion — not days, and certainly not the 6 days Nelson advertises. For programs requiring USP <71> product sterility testing, traditional 14-day incubation still applies." },
  { q: "Are Boulder BioLabs methods compliant with ISO 11737 and USP standards?", a: "Boulder BioLabs executes microbiology testing protocols aligned with ISO 11737-1, ISO 11737-2, USP <71>, USP <85>, and ISO 10993-7, operating under the Boulder BioMed ISO 13485 quality management system. Lab-level method accreditations (A2LA, ISO 17025) are in progress." },
  { q: "Do I need a method suitability study before sterility testing?", a: "Yes. Method suitability (bacteriostasis/fungistasis, or B/F) is a regulatory prerequisite under ISO 11737-2 and USP <71>. Without a documented method suitability study, your sterility test result is not defensible to FDA or a Notified Body inspector. We bundle method suitability into every new sterility program by default." },
  { q: "Can you test devices sterilized at another contract sterilizer?", a: "Yes. While our co-location advantage is strongest for Boulder Sterilization clients, we accept devices sterilized at other contract sterilizers via temperature-controlled freight. Chain of custody is documented in our LIMS at receipt." },
  { q: "What's the difference between EO residuals and CD residuals testing?", a: "EO residuals testing measures ethylene oxide, ethylene chlorohydrin (ECH), and ethylene glycol (EG) using GC-FID analysis, aligned with ISO 10993-7. CD residuals testing measures residual chlorine dioxide plus its degradation products (chlorite, chlorate) using ion chromatography and spectrophotometric methods. The two are completely different analytical workflows." },
  { q: "How many samples do I need to submit?", a: "Sample quantities vary by test and program type. For routine bioburden monitoring, the validated sampling plan typically calls for 10 devices per lot. For EO sterilization validation under ISO 11135, sample sizes are larger and depend on the validation protocol (half-cycle, full-cycle, PCD studies). Sterility testing for validation typically requires 10+ samples. We'll quote exact quantities based on your specific program scope." },
  { q: "Do you provide bioburden trend reports for routine monitoring?", a: "Yes. Clients on quarterly or recurring bioburden monitoring programs receive rolling trend data alongside individual lot reports. Trend visibility helps detect process drift before it triggers a sterility failure." },
  { q: "What endotoxin limits should I use for my device?", a: "FDA guidance sets typical limits at 0.5 EU/mL or 20 EU/device for most blood-contacting devices, with stricter thresholds for CSF-contacting devices (2.15 EU/device) and ophthalmic devices. Your specific limit depends on patient contact route and duration. Our LAL/BET team will help confirm the appropriate limit during quote scoping." },
  { q: "Which LAL method should I use?", a: "We support gel-clot, kinetic turbidimetric, and kinetic chromogenic LAL methods. Method selection depends on device material, expected endotoxin range, and prior inhibition/enhancement data. For high-volume routine release, kinetic chromogenic is typically fastest. For low-volume one-off testing, gel-clot may be most cost-effective." },
  { q: "Can you support 510(k) submissions?", a: "Yes. Our reports are formatted for inclusion in 510(k) submissions and prior approval supplements. For full regulatory submission support — pre-sub meetings, predicate selection, narrative drafting — we partner with Boulder Regulatory and Quality (Boulder RA/QA), our sister company in the Boulder BioMed family." },
  { q: "How much does sterility testing cost?", a: "Pricing varies by test type, sample count, method (direct inoculation vs. membrane filtration), and whether method suitability is included. We send detailed scope and price quotes within one business day of receiving your project description." },
  { q: "What if my sterility test fails?", a: "Positive sterility results are sub-cultured and identified to genus level (or species, on request) to support root cause investigation. We'll work with your QA team and, if relevant, with the Boulder Sterilization cycle development team to identify whether the failure was a process issue, sample contamination, or laboratory artifact. Investigation reports are issued under our ISO 13485 QMS." },
  { q: "Are you A2LA accredited or ISO 17025 accredited?", a: "Not yet. Boulder BioLabs operates under the Boulder BioMed ISO 13485 quality management system, with microbiology testing protocols aligned with ISO 11737, USP, and ISO 10993 standards. Lab-level A2LA and ISO 17025 accreditation are in progress. We disclose this transparently rather than implying accreditations we don't hold." },
  { q: "How do I request a quote?", a: "Tell us your device, sterilization method, tests needed, sample quantity, and timeline. We respond with scope and price within one business day." },
];
